# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scheduledpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="scheduledpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("publishing", "Publishing"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(fields=["celery_task_id"], name="facebook_po_celery__b41146_idx"),
        ),
    ]
