# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_post", "0002_scheduledpost_publishing_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledpost",
            name="last_celery_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["last_celery_task_id"],
                name="facebook_po_last_ce_a47fb8_idx",
            ),
        ),
    ]
