# Generated by Django 6.0.4 on 2026-05-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_post', '0003_scheduledpost_last_celery_task_id_and_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('primary_text', models.TextField()),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link_url', models.URLField()),
                ('image', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('daily_budget', models.PositiveIntegerField(default=10000)),
                ('meta_campaign_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_adset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_creative_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_ad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_image_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='facebook_po_status_36e934_idx'), models.Index(fields=['celery_task_id'], name='facebook_po_celery__b498df_idx')],
            },
        ),
    ]
