# Generated by Django 6.0.4 on 2026-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_post', '0004_scheduledad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
