# Generated by Django 6.0.4 on 2026-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_post', '0005_alter_scheduledad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledad',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('pending', 'Pending'), ('publishing', 'Publishing'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
