# Generated by Django 6.0.4 on 2026-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_post', '0006_alter_scheduledad_status_alter_scheduledpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
